# Generated by Django 2.2.4 on 2020-12-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_popular', models.CharField(max_length=200, null=True)),
                ('nombre_cientifico', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_popular', models.CharField(max_length=200, null=True)),
                ('nombre_cientifico', models.CharField(max_length=200)),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantas.Familia')),
            ],
        ),
    ]
