# Generated by Django 2.2.4 on 2020-12-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SE', 'Semillero'), ('SI', 'Siembra'), ('TR', 'Trasplante'), ('CO', 'Cosecha')], max_length=200)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sustrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierra', models.CharField(max_length=200, null=True)),
                ('potasio', models.BooleanField(default=False)),
                ('nitrogeno', models.BooleanField(default=False)),
                ('fosforo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('FR', 'Fruta'), ('FL', 'Flor'), ('HO', 'Hoja'), ('RA', 'Raiz')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='planta',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantas', to='plantas.Familia'),
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fuente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citada_en_tips', to='plantas.Fuente')),
            ],
        ),
        migrations.CreateModel(
            name='Rotaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anterior', to='plantas.Familia')),
                ('posterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posterior', to='plantas.Familia')),
            ],
        ),
        migrations.CreateModel(
            name='Interacciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('B', 'Benéfica'), ('P', 'Perjudicial')], max_length=200)),
                ('actores', models.ManyToManyField(to='plantas.Planta')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaciones', to='plantas.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_mazeta_ltr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tamano', models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande')], max_length=200)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horas_sol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('riego', models.CharField(choices=[('c15D', 'Cada 15 días'), ('1xS', 'Una vez por semana'), ('2xS', 'Dos veces por semana'), ('c2D', 'Cada dos días'), ('1xD', 'Una vez por día'), ('2xD', 'Dos veces por día')], max_length=200)),
                ('tiempo_cultivo_dias', models.IntegerField()),
                ('tutorado', models.BooleanField(default=False)),
                ('epoca_cosecha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_cosecha', to='plantas.Epoca')),
                ('epoca_semillero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_semillero', to='plantas.Epoca')),
                ('epoca_siembra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_siembra', to='plantas.Epoca')),
                ('epoca_trasplante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_trasplante', to='plantas.Epoca')),
                ('fuentes', models.ManyToManyField(to='plantas.Fuente')),
                ('planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='plantas.Planta')),
                ('sustrato', models.ManyToManyField(to='plantas.Sustrato')),
                ('tips', models.ManyToManyField(to='plantas.Tip')),
            ],
        ),
    ]
