# Generated by Django 2.2.4 on 2020-12-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_auto_20201206_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='especie',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
