# Generated by Django 2.2.4 on 2020-12-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_planta_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='desde',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta',
            field=models.DateField(null=True),
        ),
    ]
