# Generated by Django 2.2.4 on 2020-12-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_auto_20201207_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='tipo',
            field=models.CharField(choices=[('SE', 'Semillero'), ('SI', 'Siembra'), ('TR', 'Trasplante'), ('CO', 'Cosecha')], max_length=200, null=True),
        ),
    ]
