# Generated by Django 2.2.4 on 2020-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_auto_20201207_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='autor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
