# Generated by Django 2.2.4 on 2020-12-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0006_auto_20201207_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoca',
            name='estacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
