# Generated by Django 2.2.4 on 2020-12-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0007_epoca_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
