# Generated by Django 2.2.4 on 2020-12-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0009_rotaciones_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='nombre_cientifico',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
