# Generated by Django 2.2.4 on 2020-12-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0010_auto_20201208_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoca',
            name='estacion',
        ),
        migrations.AlterField(
            model_name='epoca',
            name='desde',
            field=models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], default='ENE', max_length=200),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta',
            field=models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], default='DIC', max_length=200),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='tipo',
            field=models.CharField(choices=[('SE', 'Semillero'), ('SI', 'Siembra'), ('TR', 'Trasplante'), ('CO', 'Cosecha')], default='SI', max_length=200),
        ),
    ]
