# Generated by Django 2.2.4 on 2020-12-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0011_auto_20201208_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='especie',
            new_name='variedad',
        ),
    ]
